version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: metadata_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: metadata
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql